#ifndef CONFIG_CONF_EXTINT_H_
#define CONFIG_CONF_EXTINT_H_

#if (EXTINT_CLOCK_SELECTION == EXTINT_CLK_GCLK)
#define EXTINT_CLOCK_SOURCE      GCLK_GENERATOR_0
#endif

#endif  // CONFIG_CONF_EXTINT_H_
